# -*- coding: utf-8 -*-
"""sentilyzer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hEsVmA5l-i5dl5X3fc_4l8BSP8sWXJXz
"""
import sys

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

import pandas as pd

data = pd.read_csv("./feedback_dataset.csv")

X = data['text']
y = data['category']

# Create a TF-IDF Vectorizer
tfidf_vectorizer = TfidfVectorizer()

# Transform the text data into TF-IDF features
X_tfidf = tfidf_vectorizer.fit_transform(X)

# Create a Logistic Regression classifier
classifier = LogisticRegression()

# Train the classifier
classifier.fit(X_tfidf, y)

# Function to predict sentiment
def predict_sentiment(text):
    text_tfidf = tfidf_vectorizer.transform([text])
    prediction = classifier.predict(text_tfidf)
    return prediction[0]


if __name__ == '__main__':
    text = sys.argv[1]
    #print(text)
    res = predict_sentiment(text)
    print(res)


