# -*- coding: utf-8 -*-
"""sentilyzer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hEsVmA5l-i5dl5X3fc_4l8BSP8sWXJXz
"""
import sys
import joblib
from sklearn.feature_extraction.text import TfidfVectorizer
from tensorflow.keras.datasets import imdb

# Load the IMDb dataset
max_words = 10000
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=max_words)
tfidf_vectorizer = TfidfVectorizer(stop_words='english')
x_train_tfidf = tfidf_vectorizer.fit_transform(x_train)
text = sys.argv[0]
# Load Logistic Regression model from disk
loaded_lr_model = joblib.load('logistic_regression_model.joblib')

# Predict sentiment using Logistic Regression
res_lr = loaded_lr_model.predict(tfidf_vectorizer.transform([text]))[0]
print(f"Sentiment prediction using Logistic Regression: {res_lr}")

# Load SVM model from disk
loaded_svm_model = joblib.load('svm_model.joblib')

# Predict sentiment using SVM
res_svm = loaded_svm_model.predict(tfidf_vectorizer.transform([text]))[0]
print(f"Sentiment prediction using SVM: {res_svm}")